uploads = []
generated = []

[[outputs]]
id = "Kal8XnAjJkiHebAZo_G92"
uri = "file://dealscore.zip"
type = "unspecified"
title = "DealScore — Production Build (dealscore.zip)"

[[outputs]]
id = "FHaJwiwU_JO2-J1yi0OHQ"
uri = "file://dealscore-stage3.zip"
type = "unspecified"
title = "dealscore-stage3.zip"

[[outputs]]
id = "CarMjed6FStBh0CCiYXIq"
uri = "file://dealscore-stage4.zip"
type = "unspecified"
title = "DealScore Stage 4 — Production Build"

[[outputs]]
id = "NZPqQFsujK6tjtCTuCreM"
uri = "file://dealscore-stage5-wip.zip"
type = "unspecified"
title = "dealscore-stage5-wip.zip"

[[outputs]]
id = "iQ1hvDtf_KhmzotEEN1Hr"
uri = "file://dealscore-stage5-wip2.zip"
type = "unspecified"
title = "dealscore-stage5-wip2.zip"

[[outputs]]
id = "884pvVzFHdaNA--3iwjia"
uri = "file://dealscore-stage5.zip"
type = "unspecified"
title = "dealscore-stage5.zip"
